/**
 * Design system — the one file you edit to rebrand the whole video.
 *
 * Take colors from a brand kit or a clean logo export, never from a video
 * frame or a screenshot: compression shifts them, and the drift is visible
 * once the color sits next to the real one.
 */
import { loadFont } from "@remotion/google-fonts/Inter";

// Load only the weights and subsets actually used. The unrestricted call
// fetches well over a hundred files on every render worker, which slows the
// render down and makes it fail outright on a bad connection.
const { fontFamily } = loadFont("normal", {
  weights: ["400", "600", "800", "900"],
  subsets: ["latin", "latin-ext"],
});

export const color = {
  bg: "#0B0D12",
  bgDeep: "#05070B",
  surface: "#161B25",
  surfaceEdge: "#2A3242",

  text: "#FFFFFF",
  textMuted: "#A3AEC2",

  /** Placeholder brand colors — replace these two with your own. */
  accent: "#7C5CFF",
  accent2: "#00E5A0",

  /** Caption highlight. High contrast on any background, which is the point. */
  captionActive: "#FFE55C",

  shadow: "rgba(0, 0, 0, 0.45)",
} as const;

export const font = {
  family: `${fontFamily}, "Segoe UI", system-ui, -apple-system, sans-serif`,
  regular: 400,
  medium: 600,
  bold: 800,
  black: 900,
} as const;

/** Type scale in px, sized for a 1080x1920 canvas viewed on a phone. */
export const scale = {
  hook: 108,
  title: 82,
  body: 46,
  label: 32,
  stat: 200,
  caption: 64,
} as const;

export const space = {
  margin: 72,
  gap: 28,
  pad: 40,
  radius: 32,
} as const;

/**
 * Space the platform UI covers. Keep anything that must be read outside of it.
 *
 * Bottom is the expensive one: TikTok stacks the username, the description and
 * the music ticker there, and Reels puts its own caption in roughly the same
 * band. Text that lands inside it is not "a bit tight" — it is unreadable for
 * most of the audience.
 */
export const safe = {
  top: 140,
  bottom: 380,
  right: 160,
  left: 40,
} as const;

/**
 * The band the captions own. Scenes are padded out of it, so a long line of
 * caption text can never land on top of a scene's own text — the two are
 * generated by different scripts and you would only find the collision by
 * watching the finished render.
 */
export const captionBand = 180;

/** Where the karaoke captions sit — just above the platform UI. */
export const captionBaseline = 1920 - safe.bottom - captionBand + 60;

/** Turn on in Remotion Studio to see the platform-UI overlay. Never render with it on. */
export const SHOW_SAFE_AREAS = false;
